GO
USE UnderTheSeaDB

GO
CREATE TABLE Tickets(
	ID BIGINT IDENTITY PRIMARY KEY,
	DATE_CREATED DATE
)

GO
SELECT * FROM Tickets

GO
CREATE TABLE Workers(
	ID BIGINT IDENTITY PRIMARY KEY,
	WORKERUSERNAME VARCHAR(50),
	WORKERPASSWORD VARCHAR(50),
	WORKERNAME VARCHAR(100),
	WORKERGENDER VARCHAR(10),
	WORKERSALARY INT,
	WORKERDOB DATE,
	WORKERPOSITION VARCHAR(20),
	ACTIVEWORKER INT,
	PERFORMANCEINDEX INT,
	WANTSRESIGN INT
)

/*
	WORKERPOSITION
	ATTR - Attraction Department
	MAIN - Maintenance Department
	RIAC - Ride & Attraction Creative Department
	CONS - Construction Department
	DIRO - Dining Room Division
	KITC - Kitchen Division
	PURC - Purhasing Department
	ACFI - Accounting & Finance Department
	FROF - Front Office Division
	HOKE - House Keeping Division
	SAMA - Sales Marketing Department
	HURD - Human Resource Department
	MANA - Manager
*/

GO
SELECT * FROM Workers

GO
CREATE TABLE Audits(
	ID INT IDENTITY PRIMARY KEY,
	AUDITDATE DATE,
	DEPARTMENT VARCHAR(20),
	AMOUNT INT
)

GO
SELECT * FROM Audits

CREATE TABLE Attractions(
	ID INT IDENTITY PRIMARY KEY,
	ATTRACTIONNAME VARCHAR(50),
	CAPACITY INT,
	LASTMAINTENANCE DATE,
	UPMAINTENANCE DATE,
	ATTRACTIONSTATUS VARCHAR(10),
	CONSTRUCTIONSTATUS VARCHAR(10),
	ISACTIVE INT
)

/*
	ATTRACTIONSTATUS
	MAINTAINED
	FIXING
	BROKEN

	CONSTRUCTIONSTATUS
	ESTABLISH	-> Base - Udh Berdiri
	WORKING		-> Lagi Progress
	CONSTRUCT	-> Perlu Dibuat
	UPGRADE		-> Perlu Dimodif
	REMOVAL		-> Perlu DiHancurin
	DESTROYED	-> Dah Hancur
*/

GO
SELECT * FROM Attractions

GO
CREATE TABLE GeneralReports(
	ID INT IDENTITY PRIMARY KEY,
	REPORTDATE DATE,
	DEPARTMENT VARCHAR(20),
	CONTENT VARCHAR(1000)
)
	
GO
SELECT * FROM GeneralReports

GO
CREATE TABLE ConfirmationReports(
	ID INT IDENTITY PRIMARY KEY,
	REPORTDATE DATE,
	DEPARTMENT VARCHAR(20),
	CONTENT VARCHAR(1000),
	APPROVED INT,
	RECEIVER VARCHAR(20)
)

GO
SELECT * FROM ConfirmationReports

GO
CREATE TABLE OrderScripts(
	ID INT IDENTITY PRIMARY KEY,
	DATE_CREATED DATE,
	AMOUNT INT,
	ORDERSTATUS VARCHAR(20),
	ISPAY INT,
	CHAIRNUM INT
)

GO
SELECT * FROM OrderScripts

/*
	CHAIRNUM -> NO KURSI
	ISPAY -> UDAH BAYAR ATO BLM

	NTAR VALIDASI AJA
	YANG ISPAY = 0 DENGAN CHAIRNUM SEGINI

	ORDERSTATUS
	CREATED
	COOKED
	MADE
	DELIVERED
	FINISH
*/

GO
CREATE TABLE Visitors(
	ID INT IDENTITY PRIMARY KEY,
	VISITORNAME VARCHAR(100),
	EMAIL VARCHAR(100)
)

GO
SELECT * FROM Visitors

GO
CREATE TABLE Reservations(
	ID INT IDENTITY PRIMARY KEY,
	DATE_CREATED DATE,
	VID INT FOREIGN KEY REFERENCES Visitors(ID),
	ROOMNUM INT,
	CHECKIN DATE,
	CHECKOUT DATE,
	DAMAGEFEE INT,
)

INSERT INTO Reservations (DATE_CREATED, VID, ROOMNUM, CHECKIN, CHECKOUT,DAMAGEFEE)
VALUES('2020-06-05',3,7,'2020-06-09','2020-06-10',50000)

GO
SELECT * FROM Reservations

GO
CREATE TABLE Ads(
	ID INT IDENTITY PRIMARY KEY,
	DATE_CREATED DATE,
	CONTENT VARCHAR(1000),
	ISACTIVE INT
)

GO
INSERT INTO Ads (DATE_CREATED, CONTENT, ISACTIVE)
VALUES
('2020-06-05','Demo Ads', 0),
('2020-06-07','New Title Ads for ', 1),
('2020-06-09','Demo Ads Proto 1', 0)

GO
SELECT * FROM Ads

GO
CREATE TABLE PermitReports(
	ID INT IDENTITY PRIMARY KEY,
	WID BIGINT FOREIGN KEY REFERENCES Workers(ID),
	APPROVED INT,
	CONTENT VARCHAR(1000)
)

GO
INSERT INTO PermitReports (WID,APPROVED, CONTENT)
VALUES
(1,0,'I want to take a break')

GO
SELECT * FROM PermitReports